name: Lint prose

on:
  push:
    branches-ignore:
      - master
  pull_request_target:
    branches:
      - master
    paths:
      - docs/src/documents/**
      - .github/styles/**
      - .vale.ini
      - packages/orbit-components/src/**/*.md

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      # https://github.com/errata-ai/vale-action/issues/39
      - name: Touch markdown file
        run: touch docs/src/snippets/more-than-color.mdx

      - name: Vale
        uses: errata-ai/vale-action@v1.4.1
        with:
          files: '["docs/src/documentation", "docs/src/snippets"]'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
