name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env: # Set environment variables for every job and step in this workflow
  CLICOLOR: "1" # Enable colors for *NIX commands
  PY_COLORS: "1" # Enable colors for Python-based utilities
  FORCE_COLOR: "1" # Force colors in the terminal

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Restore lerna
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock', '.yarnclean') }}

      - name: Install dependencies
        run: yarn install && yarn bootstrap

      - name: Check icons
        run: npx lerna run --scope @kiwicom/orbit-components check:icons

      - name: Build
        run: npx lerna run build

      - name: Flow
        run: yarn flow:check

      - name: TypeScript
        run: npx tsc

      - name: Lint
        run: |
          yarn eslint:ci
          yarn prettier:test

      - name: Check links
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn check-links

      - name: Test
        run: yarn test-ci
